version: '3.8'

services:
  client1:
    build:
      context: ./client1
    networks:
      - app-network

  client2:
    build:
      context: ./client2
    networks:
      - app-network

  server:
    build:
      context: ./server
    networks:
      - app-network
    ports:
      - "65432:65432/udp"
      - "65433:65433/tcp"
      - "5000:5000"
      - "80:80"       # HTTP
      - "22:22"       # SSH
      - "21:21"       # FTP
      - "23:23"       # Telnet
      - "53:53"       # DNS
      - "25:25"       # SMTP
      - "79:79"       # Finger
    cap_add:
      - NET_ADMIN
    privileged: true

networks:
  app-network:
    driver: bridge